[package]
name = "ssh-exec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-ssh2-tokio = "0.6.4"
clap = {version = "4.2.2", features = ["derive"]}
ssh2 = "0.9.4"
tokio = "1.27.0"
